#!/usr/bin/env python

import sys
import subprocess


IMAGE = "hack-the-hill-worker"

args = sys.argv
ports = args[1:]

if len(ports) < 1:
  raise ValueError("expected one or more ports")

for port in ports:
    print(f"starting on port {port}...")
    subprocess.run(["docker", "run", "-p", f"{port}:3000", "-d", IMAGE])

