#!/usr/bin/env python

import os
import sys
import subprocess


IMAGE = "hack-the-hill-worker"
TRACKER_HOST = os.getenv("TRACKER_HOST")
TRACKER_PORT = os.getenv("TRACKER_PORT")

args = sys.argv
ports = args[1:]

if len(ports) < 1:
  raise ValueError("expected one or more ports")

for port in ports:
    print(f"starting on port {port}...")
    subprocess.run(["docker", "run", "-dit", "-e", f"TRACKER_HOST={TRACKER_HOST}", "-e", f"TRACKER_PORT={TRACKER_PORT}", "-e", f"WORKER_PORT={port}", "--net", "host", IMAGE])

