version: "3.8"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    platform: linux/amd64

  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    platform: linux/amd64
