# Dockerfile.tracker
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the tracker source code
COPY tracker.js ./

# Expose the port the tracker will run on
EXPOSE 3000

# Command to run the tracker
CMD ["node", "tracker.js"]
