#!/usr/bin/env python

import sys
import subprocess


IMAGE = "hack-the-hill-tracker"

args = sys.argv

if len(args) != 2:
  raise ValueError("expected one port")

port = args[1]

subprocess.run(["docker", "run", "-p", f"{port}:3000", IMAGE])

