#!/usr/bin/env python

import subprocess
import os


TRACKER_IMAGE = "hack-the-hill-tracker"
REDIS_IMAGE = "hack-the-hill-redis"
TRACKER_PORT = os.getenv("TRACKER_PORT")
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")

subprocess.run(["docker", "run", "-e", f"TRACKER_PORT={TRACKER_PORT}", "-e", f"REDIS_HOST={REDIS_HOST}", "-e", f"REDIS_PORT={REDIS_PORT}", "-dit", "--net", "host", TRACKER_IMAGE])
subprocess.run(["docker", "run", "-p", f"{REDIS_PORT}:6379", "-dit", REDIS_IMAGE])

